FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    curl \
    unzip \
    git \
    wget \
    xz-utils \
    zip \
    libglu1-mesa \
    openjdk-17-jdk \
    lib32stdc++6 \
    clang \
    cmake \
    ninja-build \
    pkg-config \
    libgtk-3-dev

RUN git clone https://github.com/flutter/flutter.git /flutter
ENV PATH="/flutter/bin:/flutter/bin/cache/dart-sdk/bin:${PATH}"

RUN mkdir -p /opt/android-sdk && cd /opt/android-sdk \
    && wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip \
    && unzip commandlinetools-linux-11076708_latest.zip \
    && rm commandlinetools-linux-11076708_latest.zip

ENV ANDROID_HOME=/opt/android-sdk
ENV ANDROID_SDK_HOME=/opt/android-sdk
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV PATH="$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH"
RUN yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --licenses --sdk_root=/opt/android-sdk
RUN /opt/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk "platform-tools"  \
    "platforms;android-34" "build-tools;34.0.0" \
    "platforms;android-35" "build-tools;35.0.0" "cmdline-tools;latest" "ndk-bundle"
RUN /opt/android-sdk/cmdline-tools/bin/sdkmanager --update --sdk_root=/opt/android-sdk
RUN flutter config --android-sdk=/opt/android-sdk
RUN flutter doctor --android-licenses
RUN flutter precache --android
RUN flutter doctor -v
RUN useradd -ms /bin/bash flutter && echo "flutter ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
WORKDIR /home/flutter
COPY . .
RUN flutter clean
RUN flutter pub get
RUN flutter build apk
CMD ["/bin/bash"]

