// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCikFSsp_s8RWL_sZSbUm_bA1wlcp60gLU',
    appId: '1:173322126082:web:109899280bf4a517c5381b',
    messagingSenderId: '173322126082',
    projectId: 'flytech-24f17',
    authDomain: 'flytech-24f17.firebaseapp.com',
    storageBucket: 'flytech-24f17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASc8WQiXXOZ5FFG0AOUBslzNsyEIgJUCQ',
    appId: '1:173322126082:android:226bbe07afe1f695c5381b',
    messagingSenderId: '173322126082',
    projectId: 'flytech-24f17',
    storageBucket: 'flytech-24f17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANkwEG4rnmV81bzza_0cWxMAyG3eOuw5Y',
    appId: '1:173322126082:ios:94db0210069de706c5381b',
    messagingSenderId: '173322126082',
    projectId: 'flytech-24f17',
    storageBucket: 'flytech-24f17.appspot.com',
    iosBundleId: 'com.batyrov.flytech.lkmobileapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANkwEG4rnmV81bzza_0cWxMAyG3eOuw5Y',
    appId: '1:173322126082:ios:94db0210069de706c5381b',
    messagingSenderId: '173322126082',
    projectId: 'flytech-24f17',
    storageBucket: 'flytech-24f17.appspot.com',
    iosBundleId: 'com.batyrov.flytech.lkmobileapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCikFSsp_s8RWL_sZSbUm_bA1wlcp60gLU',
    appId: '1:173322126082:web:edd0fb946a06132cc5381b',
    messagingSenderId: '173322126082',
    projectId: 'flytech-24f17',
    authDomain: 'flytech-24f17.firebaseapp.com',
    storageBucket: 'flytech-24f17.appspot.com',
  );

}